version: 0.2
phases:
  install:
    runtime-versions:
      java: latest
      nodejs: latest
    commands:
     - npm install -g snyk
  build:
    commands:
      - snyk auth $SNYK_TOKEN
      - snyk test 
      - mvn verify sonar:sonar -Dsonar.projectKey=$SONAR_PROJECT_KEY -Dsonar.organization=$SONAR_PROJECT_KEY -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=$SONAR_TOKEN
      - sleep 5
      - |
        quality_status=$(curl -s -u $SONAR_TOKEN: "https://sonarcloud.io/api/qualitygates/project_status?projectKey=$SONAR_PROJECT_KEY" | jq -r '.projectStatus.status')
        echo "SonarCloud analysis status is $quality_status"
        if [ "$quality_status" = "ERROR" ]; then exit 1; fi
        

